### ISSUE TITLE
unparsable process description for landcover classification algorithm

### ISSUE THREAD

**Issue by arnevogt** [WaCoDiS/javaps-wacodis-backend#1]
Result of _DescribeProcess_ request for process _de.hsbo.wacodis.land_cover_classification_ cannot be parsed with [52North wps-client-lib](https://github.com/52North/wps-client-lib)

> 2019-03-11 14:50:53,943 [main] ERROR org.n52.geoprocessing.wps.client.WPSClientSession: Could not fetch processdescription for process: de.hsbo.wacodis.land_cover_classification
org.n52.geoprocessing.wps.client.WPSClientException: Could not decode Inputstream.
	at org.n52.geoprocessing.wps.client.WPSClientSession.parseInputStreamToString(WPSClientSession.java:551) ~[classes/:na]
	at org.n52.geoprocessing.wps.client.WPSClientSession.retrieveResponseOrExceptionReportInpustream(WPSClientSession.java:491) ~[classes/:na]
	at org.n52.geoprocessing.wps.client.WPSClientSession.retrieveDescriptionViaGET(WPSClientSession.java:564) ~[classes/:na]
	at org.n52.geoprocessing.wps.client.WPSClientSession.describeProcess(WPSClientSession.java:290) ~[classes/:na]
	at org.n52.geoprocessing.wps.client.WPSClientSession.getProcessDescription(WPSClientSession.java:229) ~[classes/:na]
	at org.n52.geoprocessing.wps.client.WPSClientExample.requestDescribeProcess(WPSClientExample.java:161) [test-classes/:na]
	at org.n52.geoprocessing.wps.client.WPSClientExample.testExecute(WPSClientExample.java:60) [test-classes/:na]
	at org.n52.geoprocessing.wps.client.WPSClientExample.main(WPSClientExample.java:176) [test-classes/:na]

This issue does not appear with the other algorithms, e.g. _de.hsbo.wacodis.snap.s2togeotiff_ or _org.n52.javaps.service.TestAlgorithm_. The issue could also be caused by _52North wps-client-lib_.

**Easiest way to reproduce:**

1. run wps web app with wacodis backend locally
2. edit variables _wpsURL_ and _processID_ in  class _org.n52.geoprocessing.wps.client.WPSClientExample.java_  of _52North wps-client-lib_
3. run _org.n52.geoprocessing.wps.client.WPSClientExample.java_ (exception is already raised when retrieving process description).

**Manually retrieving process description:** 

**unparsable** response for _de.hsbo.wacodis.land_cover_classification_: [DescribeProcess](http://localhost:8080/wps/service?service=WPS&request=DescribeProcess&identifier=de.hsbo.wacodis.land_cover_classification&version=2.0.0)
`<?xml version="1.0" encoding="UTF-8"?>
<wps:ProcessOfferings xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wps.xsd">
    <wps:ProcessOffering jobControlOptions="async-execute dismiss sync-execute" outputTransmission="value reference" processVersion="0.0.1" processModel="native">
        <wps:Process xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wps.xsd">
            <ows:Title>Land Cover Classification</ows:Title>
            <ows:Abstract>Perform a land cover classification for optical images.</ows:Abstract>
            <ows:Identifier>de.hsbo.wacodis.land_cover_classification</ows:Identifier>
            <wps:Input minOccurs="1" maxOccurs="1">
                <ows:Title>Optical images source type</ows:Title>
                <ows:Abstract>The type of the source for the optical images</ows:Abstract>
                <ows:Identifier>OPTICAL_IMAGES_TYPE</ows:Identifier>
                <wps:LiteralData>
                    <wps:Format mimeType="application/xml" default="true"/>
                    <wps:Format mimeType="text/xml"/>
                    <wps:Format mimeType="text/plain"/>
                    <wps:Format mimeType="text/plain" encoding="base64"/>
                    <LiteralDataDomain default="true">
                        <ows:AllowedValues>
                            <ows:Value>Aerial_Image</ows:Value>
                            <ows:Value>Sentinel-2</ows:Value>
                        </ows:AllowedValues>
                        <ows:DataType ows:reference="https://www.w3.org/2001/XMLSchema-datatypes#string">string</ows:DataType>
                        <ows:DefaultValue>Sentinel-2</ows:DefaultValue>
                    </LiteralDataDomain>
                </wps:LiteralData>
            </wps:Input>
            <wps:Input minOccurs="1" maxOccurs="1">
                <ows:Title>Reference data type</ows:Title>
                <ows:Abstract>The type of the reference data</ows:Abstract>
                <ows:Identifier>REFERENCE_DATA_TYPE</ows:Identifier>
                <wps:LiteralData>
                    <wps:Format mimeType="application/xml" default="true"/>
                    <wps:Format mimeType="text/xml"/>
                    <wps:Format mimeType="text/plain"/>
                    <wps:Format mimeType="text/plain" encoding="base64"/>
                    <LiteralDataDomain default="true">
                        <ows:AllowedValues>
                            <ows:Value>ATKIS</ows:Value>
                            <ows:Value>MANUAL</ows:Value>
                        </ows:AllowedValues>
                        <ows:DataType ows:reference="https://www.w3.org/2001/XMLSchema-datatypes#string">string</ows:DataType>
                        <ows:DefaultValue>ATKIS</ows:DefaultValue>
                    </LiteralDataDomain>
                </wps:LiteralData>
            </wps:Input>
            <wps:Input minOccurs="1" maxOccurs="1">
                <ows:Title>Optical images sources</ows:Title>
                <ows:Abstract>Sources for the optical images</ows:Abstract>
                <ows:Identifier>OPTICAL_IMAGES_SOURCES</ows:Identifier>
                <wps:LiteralData>
                    <wps:Format mimeType="application/xml" default="true"/>
                    <wps:Format mimeType="text/xml"/>
                    <wps:Format mimeType="text/plain"/>
                    <wps:Format mimeType="text/plain" encoding="base64"/>
                    <LiteralDataDomain default="true">
                        <ows:AnyValue/>
                        <ows:DataType ows:reference="https://www.w3.org/2001/XMLSchema-datatypes#string">string</ows:DataType>
                        <ows:DefaultValue>Sentinel-2</ows:DefaultValue>
                    </LiteralDataDomain>
                </wps:LiteralData>
            </wps:Input>
            <wps:Output>
                <ows:Title>PRODUCT</ows:Title>
                <ows:Identifier>PRODUCT</ows:Identifier>
                <wps:LiteralData>
                    <wps:Format mimeType="application/xml" default="true"/>
                    <wps:Format mimeType="text/xml"/>
                    <wps:Format mimeType="text/plain"/>
                    <wps:Format mimeType="text/plain" encoding="base64"/>
                    <LiteralDataDomain default="true">
                        <ows:AnyValue/>
                        <ows:DataType ows:reference="https://www.w3.org/2001/XMLSchema-datatypes#string">string</ows:DataType>
                    </LiteralDataDomain>
                </wps:LiteralData>
            </wps:Output>
        </wps:Process>
    </wps:ProcessOffering>
</wps:ProcessOfferings>`

**parsable** response for _org.n52.javaps.service.TestAlgorithm_: [DescribeProcess](http://localhost:8080/wps/service?service=WPS&request=DescribeProcess&identifier=org.n52.javaps.service.TestAlgorithm&version=2.0.0)
`<?xml version="1.0" encoding="UTF-8"?>
<wps:ProcessOfferings xmlns:wps="http://www.opengis.net/wps/2.0" xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wps.xsd">
    <wps:ProcessOffering jobControlOptions="async-execute dismiss sync-execute" outputTransmission="value reference" processVersion="1.0.0" processModel="native">
        <wps:Process xsi:schemaLocation="http://www.opengis.net/wps/2.0 http://schemas.opengis.net/wps/2.0/wps.xsd">
            <ows:Title>org.n52.javaps.service.TestAlgorithm</ows:Title>
            <ows:Identifier>org.n52.javaps.service.TestAlgorithm</ows:Identifier>
            <wps:Input minOccurs="1" maxOccurs="1">
                <ows:Title>input2</ows:Title>
                <ows:Identifier>input2</ows:Identifier>
                <wps:LiteralData>
                    <wps:Format mimeType="application/xml" default="true"/>
                    <wps:Format mimeType="text/xml"/>
                    <wps:Format mimeType="text/plain"/>
                    <wps:Format mimeType="text/plain" encoding="base64"/>
                    <LiteralDataDomain default="true">
                        <ows:AnyValue/>
                        <ows:DataType ows:reference="https://www.w3.org/2001/XMLSchema-datatypes#string">string</ows:DataType>
                        <ows:DefaultValue/>
                    </LiteralDataDomain>
                </wps:LiteralData>
            </wps:Input>
            <wps:Input minOccurs="1" maxOccurs="1">
                <ows:Title>input1</ows:Title>
                <ows:Identifier>input1</ows:Identifier>
                <wps:LiteralData>
                    <wps:Format mimeType="application/xml" default="true"/>
                    <wps:Format mimeType="text/xml"/>
                    <wps:Format mimeType="text/plain"/>
                    <wps:Format mimeType="text/plain" encoding="base64"/>
                    <LiteralDataDomain default="true">
                        <ows:AnyValue/>
                        <ows:DataType ows:reference="https://www.w3.org/2001/XMLSchema-datatypes#string">string</ows:DataType>
                        <ows:DefaultValue/>
                    </LiteralDataDomain>
                </wps:LiteralData>
            </wps:Input>
            <wps:Output>
                <ows:Title>output2</ows:Title>
                <ows:Identifier>output2</ows:Identifier>
                <wps:LiteralData>
                    <wps:Format mimeType="application/xml" default="true"/>
                    <wps:Format mimeType="text/xml"/>
                    <wps:Format mimeType="text/plain"/>
                    <wps:Format mimeType="text/plain" encoding="base64"/>
                    <LiteralDataDomain default="true">
                        <ows:AnyValue/>
                        <ows:DataType ows:reference="https://www.w3.org/2001/XMLSchema-datatypes#string">string</ows:DataType>
                    </LiteralDataDomain>
                </wps:LiteralData>
            </wps:Output>
            <wps:Output>
                <ows:Title>output1</ows:Title>
                <ows:Identifier>output1</ows:Identifier>
                <wps:LiteralData>
                    <wps:Format mimeType="application/xml" default="true"/>
                    <wps:Format mimeType="text/xml"/>
                    <wps:Format mimeType="text/plain"/>
                    <wps:Format mimeType="text/plain" encoding="base64"/>
                    <LiteralDataDomain default="true">
                        <ows:AnyValue/>
                        <ows:DataType ows:reference="https://www.w3.org/2001/XMLSchema-datatypes#string">string</ows:DataType>
                    </LiteralDataDomain>
                </wps:LiteralData>
            </wps:Output>
        </wps:Process>
    </wps:ProcessOffering>
</wps:ProcessOfferings>`

**Comment by SebaDro** [comment]
The cause for the described issue is not located in this repository. Since the used _wps-client-lib_ contains unimplemented support for [_ows:AllowedValues_](https://github.com/52North/wps-client-lib/blob/55d628633855352ae67d6aa52137d7abb0a436a5/src/main/java/org/n52/geoprocessing/wps/client/decoder/stream/DescribeProcessResponseDecoder.java#L521-L526), the issue is regarding to https://github.com/52North/wps-client-lib/. The issue has been solved by WaCoDiS/wps-client-lib@f39057e and thus can be closed.
